config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  patch 'projects/:project_id/issues/:id/move_issue', to: 'issues#move_issue', as: 'project_issue_move_issue'
  resources :projects do
    resources :issues, only: [:destroy, :edit, :update, :show]
    resources :stages do
      resources :issues, only: [:new, :create]
    end
  end
  resources :issues, only: [] do
    resources :assignees, only: [:create, :index]
  end
  resources :assignees, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignee.rb
class Assignee < ApplicationRecord
  belongs_to :issue
  validates :assignee_username, presence: true
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :stage
  validates :title, presence: true
  has_rich_text :description
  validates :description, presence: true
  has_many :assignees, dependent: :delete_all
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :stages, dependent: :delete_all
  validates :name, presence: true
  paginates_per 8

  def collect_all_issues
    issues = []
    stages.each do |stage|
      stage.issues.each do |issue|
        issues.push(issue)
      end
    end
    issues
  end

  def project_owner?(user)
    user.id == user_id
  end
end

app/models/stage.rb
class Stage < ApplicationRecord
  belongs_to :project
  has_many :issues, dependent: :delete_all
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login
  validates :username, uniqueness: true
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end

  private

  def require_authorized
    @project = current_project
    render plain: 'Unauthorized', status: :unauthorized unless @project.project_owner?(current_user)
  end
end

app/controllers/assignees_controller.rb
class AssigneesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[create destroy]
  before_action :authenticate_user!

  def create
    @issue = current_issue
    @issue.assignees.create(assignee_params)
  end

  def index
    issue = current_issue
    assignees = issue.assignees
    render json: assignees
  end

  def destroy
    assignee = Assignee.find(params[:id])
    assignee.destroy
  end

  private

  def current_issue
    @current_issue ||= Issue.find(params[:issue_id])
  end

  def assignee_params
    params.require(:assignee).permit(:assignee_username, :issue_id, :assignee_id)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[destroy move_issue]
  before_action :authenticate_user!
  before_action :require_authorized, only: %i[new create destroy edit update]

  def new
    @project = current_project
    @stage = current_stage
    @issue = Issue.new
  end

  def create
    @project = current_project
    @stage = current_stage
    @issue = @stage.issues.create(issue_params)
    if @issue.save
      SendIssuesJob.perform_later(@project)
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @project = current_project
    @issue = current_issue
    @assignees = @issue.assignees
  end

  def destroy
    @project = current_project
    @issue = current_issue
    SendIssuesJob.perform_later(@project) if @issue.destroy
  end

  def edit
    @project = current_project
    @issue = current_issue
  end

  def update
    @project = current_project
    @issue = current_issue
    if @issue.update(issue_params)
      SendIssuesJob.perform_later(@project)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def move_issue
    @project = current_project
    @issue = current_issue
    SendIssuesJob.perform_later(@project) if @issue.update(issue_params)
  end

  private

  def current_issue
    @current_issue ||= Issue.find(params[:id])
  end

  def current_project
    @current_project ||= Project.find(params[:project_id])
  end

  def current_stage
    @current_stage ||= Stage.find(params[:stage_id])
  end

  def issue_params
    params.require(:issue).permit(:title, :description, :stage_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = search(params[:keyword]) if current_user
  end

  private

  def search(keyword)
    if keyword.present?
      Project.where("name ILIKE ?", "%#{keyword}%").order("created_at DESC").page params[:page]
    else
      current_user.projects.order("created_at DESC").page params[:page]
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized, only: %i[edit update destroy]

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.create(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @project = current_project
    @stages = @project.stages
    @issues = @project.collect_all_issues
  end

  def edit
    @project = current_project
  end

  def update
    @project = current_project
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = current_project
    flash[:error] = "Failed to delete project." unless @project.destroy
    redirect_to root_path
  end

  private

  def current_project
    @current_project ||= Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :require_authorized

  def create
    @project = current_project
    @stage = @project.stages.create(stage_params)
    SendStagesJob.perform_later(@project) if @stage.save
  end

  def destroy
    @project = current_project
    @stage = current_stage
    @stage.destroy
    SendStagesJob.perform_later(@project)
  end

  def update
    @project = current_project
    @stage = current_stage
    SendStagesJob.perform_later(@project) if @stage.update(stage_params)
  end

  private

  def current_project
    @current_project ||= Project.find(params[:project_id])
  end

  def current_stage
    @current_stage ||= Stage.find(params[:id])
  end

  def stage_params
    params.require(:stage).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignees_helper.rb
module AssigneesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/issues/_issue_form.html.erb
<h4 class="green issue-title-input"><%= f.input :title %></h4>
<h4 class="green">Description</h4>
<div class="issue-description-input spacing-below">
  <%= f.rich_text_area :description %>
</div>
<%= f.submit 'Save', class: 'btn btn-primary' %>

app/views/issues/edit.html.erb
<div class="container">
  <div class="box text-center col-8">
    <h2 class="green spacing-below">Edit This Issue</h2>
    <%= simple_form_for @issue, url: project_issue_path(@project) do |f| %>
      <%= render partial: "issue_form", locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/issues/new.html.erb
<div class="container">
  <div class="box text-center col-8">
    <h2 class="green spacing-below">Open a new issue</h2>
    <%= simple_form_for @issue, url: project_stage_issues_path(@project, @stage) do |f| %>
      <%= render partial: "issue_form", locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/issues/show.html.erb
<div class="page-content">
  <h4 class="green col-6 issue-details-box spacing-below">
    <%= @issue.title %>
    <hr>
    <%= @issue.description %>
  </h4>
  <h4 class="spacing-below"><%= link_to "Go to project board", project_path(@project), class: "green" %></h4>
  <h4 class="spacing-below"><%= link_to "Homepage", root_path, class: "green" %></h4>
  <%= react_component("Assignees", {
    root_url: root_url,
    issue: @issue,
    current_user: current_user,
    assignees: @assignees,
    project: @project
  }) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projecttracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="header-color header-element">
        <h4><%= link_to "Homepage", root_path, class: "green" %></h4>
        <h4><%= link_to "Github", href="https://github.com/Learningstuff98/project-tracker", class: "green" %></h4>
        <h4><%= link_to "Linkedin", href="https://www.linkedin.com/in/andy-strube-6231ba152", class: "green" %></h4>
        <h4><%= link_to "Resume", href="https://docs.google.com/document/d/1qm4nBdIZfsx8zh4IwYvkVuQYclpOXUCVxnC9vV3_eBM/edit", class: "green" %></h4>
        <h4 class="green">andystrube64@gmail.com</h4>
      </div>
    </div>

    <nav class="navbar header-color green">
      <div class="container-fluid">
        <div type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
          <h4>More Info</h4>
        </div>
        <% if current_user %>
          <h4><%= "Logged in as #{current_user.username}" %></h4>
        <% end %>
      </div>
    </nav>

    <h4 class="green text-center">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </h4>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="box text-center col-8 spacing-below">
    <% if current_user %>
      <h3 class="spacing-below"><%= link_to "Start a project", new_project_path, class: "green" %></h3>
      <h3><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "green" %></h3>
    <% else %>
      <h3 class="spacing-below"><%= link_to "Log in", new_user_session_path, class: "green" %></h3>
      <h3><%= link_to "Sign up", new_user_registration_path, class: "green" %></h3>
    <% end %>
  </div>
</div>

<% if current_user %>
  <div class="text-center spacing-below">
    <%= form_tag(root_path, method: "get") do %>
      <div class="spacing-below">
        <%= text_field_tag(:keyword, nil, placeholder: 'project name', :class => "col-6 col-sm-5 col-md-5 col-lg-4 col-xl-3") %>
      </div>
      <%= submit_tag("Search", :class => "btn btn-primary") %>
    <% end %>
  </div>

  <h4 class="container spacing-below">
    <%= paginate @projects %>
  </h4>

  <% @projects.each do |project| %>
    <div class="container">
      <h3 class="spacing-below"><%= link_to project.name, project_path(project), class: "green" %></h3>
    </div>
  <% end %>
<% end %>

app/views/projects/_project_form.html.erb
<h4 class="green spacing-below"><%= f.input :name %></h4>
<%= f.submit 'Save', class: 'btn btn-primary' %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="box text-center col-8">
    <h2 class="green spacing-below">Edit this project</h2>
    <%= simple_form_for @project, url: project_path(@project) do |f| %>
      <%= render partial: "project_form", locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="box text-center col-8">
    <h2 class="green spacing-below">Start a new project</h2>
    <%= simple_form_for @project, url: projects_path do |f| %>
      <%= render partial: "project_form", locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="green page-content">
  <h4><%= "Project name: #{@project.name}" %></h4>
  <% if @project.project_owner?(current_user) %>
    <h4><%= link_to 'Edit this project', edit_project_path(@project), class: "green" %></h4>
    <h4><%= link_to "Delete this project", project_path(@project), method: :delete, data: { confirm: "Are you sure?" }, class: "green"%></h4>
  <% end %>
  <h4 class="spacing-below"><%= link_to 'Homepage', root_path, class: "green" %></h4>

  <%= react_component("Project", {
    project: @project,
    stages: @stages,
    root_url: root_url,
    current_user: current_user,
    issues: @issues
  }) %>
</div>